import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='grid grid-cols-12 auto-rows-min gap-y-4 min-h-dvh bg-sky-200'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
